title: "👋 Hello from {Name/Handle}"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        <img src="https://github.com/user-attachments/assets/e783c2de-cd6b-4576-9663-96bd0fb29391" />

        # Welcome
        This space is for introductions. Say hi, share what you are excited about, and meet other folks.

        ## Where should this go
        If your post is really about how to use GitHub or troubleshooting, please post in New to GitHub or the most relevant help category so you can get the best answers.

        ## Privacy and safety
        Please do not share sensitive personal info such as addresses, phone numbers, or private emails.

        ## One intro per person
        Please make one intro discussion and share updates later as replies anytime.

        ## Keep it friendly and human
        A couple links are fine, just keep them secondary to your intro. Avoid link dumping, recruiting, or promo only posts.

        Conversation starter
        End with Ask me about or Say hi if you also like

  - type: input
    id: name
    attributes:
      label: "What should we call you? (optional)"
      description: "First name, handle, or whatever you prefer. No real name required."
      placeholder: "e.g., Samus, @samus-aran, Sam"
    validations:
      required: false

  - type: dropdown
    id: journey
    attributes:
      label: "Where are you in your GitHub journey?"
      description: "Pick the closest match. There is no wrong answer."
      options:
        - "Brand new to GitHub"
        - "Student or learning the basics"
        - "Building my first project"
        - "Contributing to open source"
        - "Maintaining a project or repo owner"
        - "Here to make connections"
        - "Other"
    validations:
      required: true

  - type: checkboxes
    id: interest_areas
    attributes:
      label: "Interest areas (optional)"
      description: "Choose a few broad topics, then add your own tags below."
      options:
        - label: "Open source"
        - label: "Accessibility"
        - label: "Git basics"
        - label: "GitHub features and news"
        - label: "Actions or CI"
        - label: "Docs"
        - label: "Security"
        - label: "Dev tools"
        - label: "API or integrations"
        - label: "Project management"
        - label: "Community building"
        - label: "Other"
    validations:
      required: false

  - type: input
    id: interest_tags
    attributes:
      label: "In 2 to 3 words, what are you interested in on GitHub? (optional)"
      description: "Think of these like mini tags. Examples include design systems, Python, issue triage, docs."
      placeholder: "e.g., accessibility testing; GitHub Actions; documentation"
    validations:
      required: false

  - type: textarea
    id: learn_build
    attributes:
      label: "What are you hoping to learn or build next?"
      description: "A sentence or two is perfect."
      placeholder: "I am hoping to… I am building… Next I want to try…"
    validations:
      required: true

  - type: dropdown
    id: fun_extra
    attributes:
      label: "A fun extra (optional)"
      description: "Choose one prompt or skip it."
      options:
        - "Favorite tool right now"
        - "Currently learning"
        - "Fun fact"
        - "Your ask me about topic"
        - "Something you are proud of"
        - "Other"
    validations:
      required: false

  - type: textarea
    id: fun_answer
    attributes:
      label: "Your fun extra (optional)"
      description: "Keep it light and inviting."
      placeholder: "Ask me about… Fun fact… Currently learning…"
    validations:
      required: false

  - type: textarea
    id: links
    attributes:
      label: "Optional links (optional)"
      description: "If you want, share your GitHub profile and or one relevant repo. Keep it secondary to your intro."
      placeholder: |
        https://github.com/your-handle
        https://github.com/your-handle/your-repo
    validations:
      required: false
